// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// IControllerGeneric is an autogenerated mock type for the IControllerGeneric type
type IControllerGeneric[T interface{}, X interface{ string | uint }] struct {
	mock.Mock
}

type IControllerGeneric_Expecter[T interface{}, X interface{ string | uint }] struct {
	mock *mock.Mock
}

func (_m *IControllerGeneric[T, X]) EXPECT() *IControllerGeneric_Expecter[T, X] {
	return &IControllerGeneric_Expecter[T, X]{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *IControllerGeneric[T, X]) Create(_a0 context.Context, _a1 T) (T, error) {
	ret := _m.Called(_a0, _a1)

	var r0 T
	if rf, ok := ret.Get(0).(func(context.Context, T) T); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(T)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IControllerGeneric_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type IControllerGeneric_Create_Call[T interface{}, X interface{ string | uint }] struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 T
func (_e *IControllerGeneric_Expecter[T, X]) Create(_a0 interface{}, _a1 interface{}) *IControllerGeneric_Create_Call[T, X] {
	return &IControllerGeneric_Create_Call[T, X]{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *IControllerGeneric_Create_Call[T, X]) Run(run func(_a0 context.Context, _a1 T)) *IControllerGeneric_Create_Call[T, X] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T))
	})
	return _c
}

func (_c *IControllerGeneric_Create_Call[T, X]) Return(_a0 T, _a1 error) *IControllerGeneric_Create_Call[T, X] {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Delete provides a mock function with given fields: _a0
func (_m *IControllerGeneric[T, X]) Delete(_a0 *gin.Context) {
	_m.Called(_a0)
}

// IControllerGeneric_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type IControllerGeneric_Delete_Call[T interface{}, X interface{ string | uint }] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 *gin.Context
func (_e *IControllerGeneric_Expecter[T, X]) Delete(_a0 interface{}) *IControllerGeneric_Delete_Call[T, X] {
	return &IControllerGeneric_Delete_Call[T, X]{Call: _e.mock.On("Delete", _a0)}
}

func (_c *IControllerGeneric_Delete_Call[T, X]) Run(run func(_a0 *gin.Context)) *IControllerGeneric_Delete_Call[T, X] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *IControllerGeneric_Delete_Call[T, X]) Return() *IControllerGeneric_Delete_Call[T, X] {
	_c.Call.Return()
	return _c
}

// Get provides a mock function with given fields: _a0
func (_m *IControllerGeneric[T, X]) Get(_a0 *gin.Context) {
	_m.Called(_a0)
}

// IControllerGeneric_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type IControllerGeneric_Get_Call[T interface{}, X interface{ string | uint }] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 *gin.Context
func (_e *IControllerGeneric_Expecter[T, X]) Get(_a0 interface{}) *IControllerGeneric_Get_Call[T, X] {
	return &IControllerGeneric_Get_Call[T, X]{Call: _e.mock.On("Get", _a0)}
}

func (_c *IControllerGeneric_Get_Call[T, X]) Run(run func(_a0 *gin.Context)) *IControllerGeneric_Get_Call[T, X] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *IControllerGeneric_Get_Call[T, X]) Return() *IControllerGeneric_Get_Call[T, X] {
	_c.Call.Return()
	return _c
}

// GetAll provides a mock function with given fields: _a0
func (_m *IControllerGeneric[T, X]) GetAll(_a0 *gin.Context) {
	_m.Called(_a0)
}

// IControllerGeneric_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type IControllerGeneric_GetAll_Call[T interface{}, X interface{ string | uint }] struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - _a0 *gin.Context
func (_e *IControllerGeneric_Expecter[T, X]) GetAll(_a0 interface{}) *IControllerGeneric_GetAll_Call[T, X] {
	return &IControllerGeneric_GetAll_Call[T, X]{Call: _e.mock.On("GetAll", _a0)}
}

func (_c *IControllerGeneric_GetAll_Call[T, X]) Run(run func(_a0 *gin.Context)) *IControllerGeneric_GetAll_Call[T, X] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *IControllerGeneric_GetAll_Call[T, X]) Return() *IControllerGeneric_GetAll_Call[T, X] {
	_c.Call.Return()
	return _c
}

// Update provides a mock function with given fields: _a0, _a1, _a2
func (_m *IControllerGeneric[T, X]) Update(_a0 context.Context, _a1 X, _a2 T) (int, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, X, T) int); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, X, T) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IControllerGeneric_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type IControllerGeneric_Update_Call[T interface{}, X interface{ string | uint }] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 X
//   - _a2 T
func (_e *IControllerGeneric_Expecter[T, X]) Update(_a0 interface{}, _a1 interface{}, _a2 interface{}) *IControllerGeneric_Update_Call[T, X] {
	return &IControllerGeneric_Update_Call[T, X]{Call: _e.mock.On("Update", _a0, _a1, _a2)}
}

func (_c *IControllerGeneric_Update_Call[T, X]) Run(run func(_a0 context.Context, _a1 X, _a2 T)) *IControllerGeneric_Update_Call[T, X] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(X), args[2].(T))
	})
	return _c
}

func (_c *IControllerGeneric_Update_Call[T, X]) Return(_a0 int, _a1 error) *IControllerGeneric_Update_Call[T, X] {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewIControllerGeneric interface {
	mock.TestingT
	Cleanup(func())
}

// NewIControllerGeneric creates a new instance of IControllerGeneric. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIControllerGeneric[T interface{}, X interface{ string | uint }](t mockConstructorTestingTNewIControllerGeneric) *IControllerGeneric[T, X] {
	mock := &IControllerGeneric[T, X]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
